language: python
cache: pip
python:
 - '3.7'
install:
 - pip install pipenv
 - pipenv install
script:
 - pipenv run cyrax
 - test 6000 -lt $(cat _build/index.html | wc -l)
 - yarn install
 - yarn danger ci
