language: python
python:
 - '2.7'
virtualenv:
  system_site_packages: true
before_install:
 - openssl aes-256-cbc -K $encrypted_61da1a775a65_key -iv $encrypted_61da1a775a65_iv -in .travis/deploy_key.enc -out .travis/deploy_key -d
 - sudo apt-get install -qq python-yaml python-jinja2 python-smartypants
install:
 - pip install cyrax
script:
 - cyrax
 - test 6000 -lt $(cat _build/index.html | wc -l)
after_success:
 - chmod 600 .travis/deploy_key
 - ssh-add .travis/deploy_key
 - git remote add maia dokku@maia.solovyov.net:osgc
 - git push deploy
