language: python
cache: pip
python:
 - '2.7'
virtualenv:
  system_site_packages: true
addons:
  ssh_known_hosts: maia.solovyov.net
install:
 - pip install cyrax
 - pip install pyyaml
script:
 - cyrax
 - test 6000 -lt $(cat _build/index.html | wc -l)
 - '[ "${TRAVIS_PULL_REQUEST}" != "false" ] || .travis/deploy.sh'
