type: seq
sequence:
  - type: map
    mapping:
      name:
        type: any
      names:
        type: any
      clones:
        type: seq
        sequence:
          - include: game
      reimplementations:
        type: seq
        sequence:
          - include: game

schema;game:
  type: map
  mapping:
    name:
      type: str
    url:
      type: str
    repo:
      type: str
    info:
      type: str
    status:
      type: str
      enum: ['playable', 'semi-playable', 'unplayable']
    development:
      type: str
      enum: ['complete', 'very active', 'active', 'sporadic', 'halted']
    license:
      include: licenses
    lang:
      type: any
    framework:
      type: any
    added:
      type: any
    media:
      type: seq
      sequence:
        - type: map
          mapping:
            raw:
              type: str
            image:
              type: str
            url:
              type: str

# Based on SPDX license codes
# https://spdx.org/licenses/
schema;licenses:
  type: str
  enum: [
    'Custom', # Catch-all for custom licenses
    'Multiple', # Catch-all for multiple licenses
    'AGPL3',
    'Apache',
    'Artistic',
    'BSD',
    'BSD2',
    'BSD4',
    'CC0',
    'CC-BY',
    'CC-BY-NC',
    'CC-BY-NC-SA',
    'CC-BY-SA',
    'GPL',
    'GPL2',
    'GPL3',
    'JRL', # Java Research License
    'LGPL',
    'LGPL2',
    'MIT',
    'MPL', # Mozilla Public License
    'MS-PL', # Microsoft Public License
    'NGPL', # Nethack General Public License,
    'WTFPL' # Do What The F*ck You Want To Public License
  ]
