- name: Some Game
  clones:
    - name: Some Free Game
      url: somefreegame.com
      repo: https://github.com/foobar/SomeFreeGame
      info: active development, playable, C++
      added: 2014-04-04
      media:
        - url: http://somefreegame.com/img1.jpg
          image: http://somefreegame.com/img1_thumbnail.jpg
        - url: http://somefreegame.com/img2.jpg
          image: http://somefreegame.com/img2_thumbnail.jpg
        - raw: <iframe width="320" height="240" src="//www.youtube.com/embed/abcdefg1234?rel=0" frameborder="0" allowfullscreen></iframe>